### PR TITLE
fix: disable create service button if name and image are empty (#48)

### LINKED ISSUE #48: Create button always enabled
In the create service wizard, the create button is always enabled even if no name or image has been specified

### PR DESCRIPTION
**Pull request by lstocchi**
it resolves #48 
It needs https://github.com/redhat-developer/intellij-common/pull/79 to work

### CODE REVIEW

File: src/main/java/com/redhat/devtools/intellij/knative/ui/CreateServiceDialog.java [hunk 1]
```diff
@@ -92,6 +96,31 @@ private void initEditor(String namespace) {
...
         editor = new PsiAwareTextEditorImpl(project, new LightVirtualFile("service.yaml", content), TextEditorProvider.getInstance());
+        editor.getEditor().getDocument().addDocumentListener(createEditorListener());
+    }
+
+    private com.intellij.openapi.editor.event.DocumentListener createEditorListener() {
+        return new com.intellij.openapi.editor.event.DocumentListener() {
+            @Override
+            public void documentChanged(com.intellij.openapi.editor.event.DocumentEvent event) {
+                try {
+                    String nameInYAML = YAMLHelper.getStringValueFromYAML(editor.getEditor().getDocument().getText(), new String[] { "metadata", "name" });
```
Comment (jeffmaury) [inline src/main/java/com/redhat/devtools/intellij/knative/ui/CreateServiceDialog.java:107]: Maybe good to have those YAML paths as constants as they are duplicated several times

**Review by jeffmaury — APPROVED** [review]
LGTM
