### PR TITLE
fix: add empty registry flag as a workaround for bug on func cli with ocp cluster

### LINKED ISSUE #152: Deploying to ocp cluster always use internal registry
To prevent it we should add an empty registry as suggested here https://github.com/knative-sandbox/kn-plugin-func/issues/941

### PR DESCRIPTION
**Pull request by lstocchi**
it resolves #152

### CODE REVIEW

File: src/main/java/com/redhat/devtools/intellij/knative/kn/KnCli.java [hunk 1]
```diff
@@ -83,6 +85,7 @@ private void reportTelemetry() {
         TelemetryMessageBuilder.ActionMessage telemetry = TelemetryService.instance().action(TelemetryService.NAME_PREFIX_MISC + "login");
         try {
             ClusterInfo info = ClusterHelper.getClusterInfo(client);
+            isOpenshift = info.isOpenshift();
```
Comment (jeffmaury) [inline src/main/java/com/redhat/devtools/intellij/knative/kn/KnCli.java:88]: `getClusterInfo` is a costly method that includes possibly several round trips to the cluster. To detect if it's an OpenShift cluster, you should use `client.isAdaptable(OpenShiftClient.class)` instead

**Review by jeffmaury — CHANGES_REQUESTED** [review]
