### PR TITLE
fix wrong behavior in create service action (#49)

### LINKED ISSUE #49: Error not shown when creating a service with the same name of an existing one

### PR DESCRIPTION
**Pull request by lstocchi**
it resolves #49 

Now it works as before. Merging the update/create action created a wrong behavior. Now errors are displayed correctly.

### CODE REVIEW

**Review by evidolob — APPROVED** [review]

File: src/main/java/com/redhat/devtools/intellij/knative/kn/ServiceDeserializer.java [hunk 1]
```diff
@@ -39,8 +39,8 @@ private ServiceStatus convertToStatus(JsonNode statusNode) {
         if (statusNode == null || statusNode.isEmpty()) {
             return null;
         }
-        String url = statusNode.get("url").asText();
-        int observedGeneration = statusNode.get("observedGeneration").asInt();
+        String url = statusNode.get("url") != null ? statusNode.get("url").asText() : "";
```
Comment (jeffmaury) [inline src/main/java/com/redhat/devtools/intellij/knative/kn/ServiceDeserializer.java:42]: There's a `has(fieldName)` method that is easier to read

**Review by jeffmaury — APPROVED** [review]
LGTM
